### ISSUE TITLE
error raised during testing of image

### ISSUE THREAD

**Issue by ZubairKhan001** [lwchen6309/unsupervised-image-segmentation-by-WNet-with-NormalizedCut#1]
File "D:\deep learning codes\unsupervised-image-segmentation-by-WNet-with-NormalizedCut\src\UNet.py", line 179, in plot_segmentation_under_test_dir
    colorized_test_preds = utils.batch_colorize_ndarray(test_preds,0, self.flags.num_class, self.flags.cmap)[:,:,:,:3]
IndexError: too many indices for array

**Comment by rahulrathnakumar** [comment]
How did you solve that issue @Laowai01 ?
@lwchen6309  Any thoughts on this error?

**Comment by kos95** [comment]
Really Need help on this...
