### ISSUE TITLE
Undefined function: unprocess_image

### ISSUE THREAD

**Issue by shamazharikh** [lwchen6309/unsupervised-image-segmentation-by-WNet-with-NormalizedCut#2]
In line 20 of TenforflowUtils.py, the method unprocess_image() is invoked, but there is no definition of this function in the code. Please add a definition.

**Comment by lwchen6309** [comment]
I removed the unprocess_image() accordingly, since there's no pre-processioning in this stage.

**Comment by lwchen6309** [comment]
> I removed the unprocess_image() accordingly, since there's no pre-processioning in this stage.
