### ISSUE TITLE
Can you resume training from an existing model?

### ISSUE THREAD

**Issue by mengwang-mw** [lwchen6309/unsupervised-image-segmentation-by-WNet-with-NormalizedCut#3]
Say you have been training this model for 500 epochs, can I resume it by loading the trained model?

**Comment by Laowai01** [comment]
getting error while training wnet_bright, please guide.
  File "D:\deep learning codes\unsupervised-image-segmentation-by-WNet-with-NormalizedCut\src\soft_ncut.py", line 456, in convert_to_batchTensor
    new_indeces = tf.concat([tile_batch,tile_indeces],axis=1)

NameError: name 'tile_indeces' is not defined

**Comment by lwchen6309** [comment]
Yes, you can resume it simply using the same "logdir"

**Comment by lwchen6309** [comment]
Yes, you can resume the training by using the same "logdir"

**Comment by rahulrathnakumar** [comment]
I used the same logdir path for retraining after the first 50,000 steps to reproduce your results. However, the validation loss and train loss are different from the values of the 49,999th step. Is this normal? Thanks!

**Comment by lwchen6309** [comment]
Hi, I think it's fine.
The loss of 2 stages is different because of different dropout rate.

**Comment by rahulrathnakumar** [comment]
Thanks a lot for the clarification! Your work is very exciting. Reading through the paper as I type!

**Comment by lwchen6309** [comment]
Hi I'm glad that my work could help. =)

rahulrathnakumar <notifications@github.com> 於 2019年3月24日 週日 上午11:13 寫道：
